/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCompraRouteImport } from './routes/_authenticated/compra'
import { Route as AuthenticatedFamiliaRouteImport } from './routes/_authenticated/familia'
import { Route as AuthenticatedSemanaRouteImport } from './routes/_authenticated/semana'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompraRoute = AuthenticatedCompraRouteImport.update({
  id: '/compra',
  path: '/compra',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamiliaRoute = AuthenticatedFamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSemanaRoute = AuthenticatedSemanaRouteImport.update({
  id: '/semana',
  path: '/semana',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compra': typeof AuthenticatedCompraRoute
  '/familia': typeof AuthenticatedFamiliaRoute
  '/semana': typeof AuthenticatedSemanaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compra': typeof AuthenticatedCompraRoute
  '/familia': typeof AuthenticatedFamiliaRoute
  '/semana': typeof AuthenticatedSemanaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/compra': typeof AuthenticatedCompraRoute
  '/_authenticated/familia': typeof AuthenticatedFamiliaRoute
  '/_authenticated/semana': typeof AuthenticatedSemanaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/compra' | '/familia' | '/semana'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/compra' | '/familia' | '/semana'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/compra'
    | '/_authenticated/familia'
    | '/_authenticated/semana'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compra': {
      id: '/_authenticated/compra'
      path: '/compra'
      fullPath: '/compra'
      preLoaderRoute: typeof AuthenticatedCompraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/familia': {
      id: '/_authenticated/familia'
      path: '/familia'
      fullPath: '/familia'
      preLoaderRoute: typeof AuthenticatedFamiliaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/semana': {
      id: '/_authenticated/semana'
      path: '/semana'
      fullPath: '/semana'
      preLoaderRoute: typeof AuthenticatedSemanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompraRoute: typeof AuthenticatedCompraRoute
  AuthenticatedFamiliaRoute: typeof AuthenticatedFamiliaRoute
  AuthenticatedSemanaRoute: typeof AuthenticatedSemanaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompraRoute: AuthenticatedCompraRoute,
  AuthenticatedFamiliaRoute: AuthenticatedFamiliaRoute,
  AuthenticatedSemanaRoute: AuthenticatedSemanaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
